development:
  ontologies:
    - CL
    - GO
    - MONDO
    - UBERON

staging:
  ontologies:
    - CL
    - GO
    - MONDO
    - UBERON

production:
  ontologies:
    - CL
    - GO
    - MONDO
    - UBERON

appliance:
  ontologies: null