test:
  ontologies:
    STY:
      repository: 'jvendetti/bioportal-nigms-u24'

development:
  ontologies:
    GO:
      repository: 'hrshdhgd/go-ontology'
    MONDO:
      repository: 'hrshdhgd/mondo'
    UBERON:
      repository: 'hrshdhgd/uberon'

staging:
  ontologies:
    GO:
      repository: 'hrshdhgd/go-ontology'
    MONDO:
      repository: 'hrshdhgd/mondo'
    UBERON:
      repository: 'hrshdhgd/uberon'

production:
  ontologies: null

appliance:
  ontologies: null