test:
  ontologies:
    STY:
      repository: 'jvendetti/bioportal-nigms-u24'

development:
  ontologies:
    GO:
      repository: 'jvendetti/bioportal-nigms-u24'
    MONDO:
      repository: 'jvendetti/bioportal-nigms-u24'
    UBERON:
      repository: 'jvendetti/bioportal-nigms-u24'

staging:
  ontologies:
    GO:
      repository: 'geneontology/go-ontology'
    MONDO:
      repository: 'monarch-initiative/mondo'
    UBERON:
      repository: 'obophenotype/uberon'

production:
  ontologies:
    GO:
      repository: 'geneontology/go-ontology'
    MONDO:
      repository: 'monarch-initiative/mondo'
    UBERON:
      repository: 'obophenotype/uberon'

appliance:
  ontologies: null